{\rtf1\ansi\ansicpg1252\cocoartf2822
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 # .streamlit/secrets.toml\
\
[google_oauth]\
client_id = "452500092831-l211d1tsd68slrsab7lo437uu0h2c80k.apps.googleusercontent.com","project_id":"streamlit-app-457905"\
client_secret = "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"\
redirect_uri = "https://app-app-dmd885trlrzjjeh3nzckr4.streamlit.app" # Or your deployed URL\
# Update the scopes list\
scopes = [\
    "https://www.googleapis.com/auth/spreadsheets.readonly",\
    "https://www.googleapis.com/auth/drive.readonly.metadata" # Add this line\
    ]}